version: '2.3'
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: jdsantos/bens-essenciais-domicilio
    restart: always
    container_name: bens_essenciais
    ports:
      - "8080:80"
  webserver:
    build: ./webserver
    container_name: webserver
    restart: always
    depends_on:
      - "app"
    ports:
      - "80:80"
    volumes:
      - ./conf-sites/sites.template:/etc/nginx/conf.d/default.conf
      - ./conf-sites/nginx.conf:/etc/nginx/nginx.conf
      - ./conf-sites/certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./conf-sites/certs/priv.pem:/etc/ssl/certs/priv.pem
      - ./conf-sites/certbot/www:/var/www/certbot